### ISSUE TITLE
HOW TO COMPILE A PROJECT

### ISSUE THREAD

**Issue by join1337** [epoll-reactor/cpp_vk_lib#37]
HOW TO COMPILE A PROJECT

**Comment by epoll-reactor** [comment]
Did you visit [this repo](https://github.com/epoll-reactor/template_cpp_vk_bot)?The library mainly designed to be used as submodule. It means, you should create the CMake project and include this library via `add_subdirectory`. Or, if you wish to run tests, type
```
cmake .. -DCMAKE_BUILD_TYPE=Release -DCPP_VK_LIB_SANITIZE=0 -DCPP_VK_LIB_BENCHMARKING=0 && cmake --build . --parallel
cd tests
ctest .
```
